from dataclasses import dataclass
from typing import Any, Optional, Protocol


@dataclass
class EngineBinary:
    content: bytes
    content_type: str
    filename: Optional[str] = None


class DetectionEnginePort(Protocol):
    """Outbound port to the construction-detection GPU service."""

    def health(self) -> dict[str, Any]: ...

    def list_wms_layers(self) -> dict[str, Any]: ...

    def start_detect_wms_async(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def get_progress(self, job_id: str) -> dict[str, Any]: ...

    def get_result(self, job_id: str) -> dict[str, Any]: ...

    def cancel_job(self, job_id: str) -> dict[str, Any]: ...

    def get_align_manual(self, job_id: str) -> dict[str, Any]: ...

    def preview_align_manual(self, job_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...

    def apply_align_manual(self, job_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...

    def get_registro_catastral(self, id_registro: int) -> dict[str, Any]: ...

    def fetch_path(self, relative_path: str) -> EngineBinary: ...

    def fetch_json(self, relative_path: str) -> dict[str, Any]: ...
