-- Dominio CITE para IDEC (PostgreSQL 14+), esquema `public`.
-- Este archivo NO se ejecuta automáticamente: el backend ya no crea estas tablas
-- (ver app/domains/cite/infrastructure/models.py). Aplíquelo con psql:
--   psql -h <host> -U <usuario> -d <base> -f database/cite_postgresql.sql
-- Es idempotente (CREATE ... IF NOT EXISTS), por lo que puede re-ejecutarse.
--
-- Los nombres de columna son los de la BASE y deben coincidir exactamente con
-- los mapeados en app/domains/cite/infrastructure/models.py.

BEGIN;

-- Tipo del campo area.tipo. PostgreSQL no tiene CREATE TYPE IF NOT EXISTS.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'area_tipo_enum') THEN
        CREATE TYPE area_tipo_enum AS ENUM ('Secretaria', 'Direccion', 'Jefatura', 'Unidad');
    END IF;
END
$$;

-- Gestión (año fiscal). El correlativo CITE se reinicia por gestión y prefijo.
CREATE TABLE IF NOT EXISTS gestion (
    id_gestion      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio            integer NOT NULL UNIQUE,
    fecha_inicial   date NOT NULL,
    fecha_final     date NOT NULL,
    activa          boolean NOT NULL DEFAULT true
);

-- Estructura orgánica de la Alcaldía, jerárquica por id_area_padre.
CREATE TABLE IF NOT EXISTS area (
    id_area         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          varchar(150) NOT NULL,
    tipo            area_tipo_enum NOT NULL,
    id_area_padre   integer REFERENCES area (id_area) ON DELETE SET NULL
);

-- Un prefijo CITE por área y gestión (p. ej. DGC en la gestión 2026).
CREATE TABLE IF NOT EXISTS configuracion_cite (
    id_configuracion    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area             integer NOT NULL REFERENCES area (id_area),
    id_gestion          integer NOT NULL REFERENCES gestion (id_gestion),
    prefijo             varchar(20) NOT NULL,
    activo              boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_configuracion_gestion_prefijo UNIQUE (id_gestion, prefijo)
);

-- Documentos con código CITE emitido.
--
-- codigo_cite_completo es GENERATED ... STORED: la aplicación nunca la escribe.
-- El cast ::text no es opcional -- lpad en PostgreSQL solo acepta
-- lpad(text, integer, text) y no convierte el integer sola. Tampoco sirve
-- concat(): está marcada STABLE y las columnas generadas exigen expresiones
-- IMMUTABLE; el operador || sí lo es.
--
-- uq_documento_configuracion_correlativo es la red de seguridad contra
-- race-conditions en la generación del correlativo (ver sql_cite_repository.py)
-- y además sirve de índice para el MAX(correlativo) por configuración.
CREATE TABLE IF NOT EXISTS documento_cite (
    id_documento                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_configuracion            integer NOT NULL REFERENCES configuracion_cite (id_configuracion),
    prefijo                     varchar(20) NOT NULL,
    correlativo                 integer NOT NULL,
    codigo_cite_completo        varchar(50) NOT NULL
                                GENERATED ALWAYS AS (prefijo || '-' || lpad(correlativo::text, 3, '0')) STORED,
    fecha_generacion            timestamp NOT NULL,
    referencia                  text NOT NULL,
    id_funcionario_remitente    integer NOT NULL,
    CONSTRAINT uq_documento_configuracion_correlativo UNIQUE (id_configuracion, correlativo)
);

COMMIT;
